repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1  # Use the latest release
    hooks:
      - id: nb-clean
        args:
          - --preserve-cell-metadata
          - tags
          - --